### ISSUE TITLE
Logistics Pipes & LoliASM crash with IC2C

### ISSUE THREAD

**Issue by jvahle3** [xJon/Tekkit-2#28] opened 2022-08-31 03:42 UTC
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

Very easy to reproduce crash.

1. Fill an IC2 gas can with Coalfuel using a canning machine
2. Place a basic IC2 generator with power consumer
3. Place filled gas can in generator fuel slot
4. Wait until fuel is all used
5. Right click generator

Game should crash.
Sometimes crashed to desktop sometimes to main menu

Tested in single player and on a locally hosted server, crashed both times.
In multiplayer looks like it causes clients to disconnect but server doesn't crash.

**Comment by Jaari** [comment] 2022-08-31 21:59
To give a bit of information on this regarding the gas can, this involves quite a few steps:

1. Make coal dust (for example macerating coal).
2. Turn coal dust into hydrated coal dust by crafting with a water bucket.
3. Turn this into H. Coal by putting it into a compressor.
4. Combine H. Coal with an empty cell in the canning machine for H. Coal Cell.
5. Put the H. Coal Cell in an Extractor to finally get the Coalfuel Cell.
6. Combine some Coalfuel Cell with an empty fuel can in the canning machine to get a filled fuel can (gas can). This gives a fuel can with 15288 "fuel" in it.
7. Wait until the can empties in a basic generator (takes a bit). Rightclick the generator when it stops. Have the game crash with the following crash: (actual crashreport seemed unhelpful, so included everything on my side from the start that I gave myself the canning machine). https://pastebin.com/ZRKCvkPZ

**Comment by Jaari** [comment] 2022-08-31 22:08
Notable addition:

Half of the fuel can in the canning machine recipes do not seem to work:
Working:
- Coalfuel cell
- Biofuel cell

Not working:
- Glowstone
- Redstone
- Gunpowder
- Fuel cell.

Weird behaviour:
- A fuel can (as opposed to the normal "filled fuel can") can be made by combining a coalfuel cell with an empty fuel can in the canning machine. However, that recipe produces the regular filled fuel can.

**Comment by Jaari** [comment] 2022-08-31 22:11
Another addition: Crash happens when keeping the GUI open, the moment the fuel can empties, the game freezes. Crash reported is the same as the initial one in the earlier paste. https://pastebin.com/Kkn6AcSS

**Comment by Speiger** [comment] 2022-08-31 23:19
@Jaari the not working ones are multipliers you cant multiply 0 to anything larger then 0.

So you put in coal/bio in first and then add glow/redstone gunpowder or fuel cell.
Since the canner stores the values and applies each item individually based on how much fuel it has cached.

Also the crashes are unrelated to ic2c, they have nothing todo with it.
One is a saving crash, the other is a logistic pipes crash.

**Comment by Jaari** [comment] 2022-09-01 11:48
The reason that IC2C was suspected was that the saving crash happens the moment you rightclick the generator which has now an empty fuel can inside. The logistics pipe crash happens shortly after the save crash, might even be caused by loliasm trying to keep the world from crashing. 

I've just tried to reproduce this using only IC2C, and for the sake of it, IC2C and logisticspipes, but was unable to reproduce.

Also, thanks for the explanation of how the fuel multipliers work. It hadn't crossed my mind that they're additions to the fuel, instead of being fuel themselves.

**Comment by Jaari** [comment] 2022-09-01 12:06
Did some more testing:

Crashes using loliasm (requires mixinbooter), logisticspipes (requires codechickenlib) and IC2C.
Doesn't crash using just loliasm and IC2C.
Doesn't crash using just logisticspipes and IC2C.

**Comment by xJon** [comment] 2022-09-01 12:56
Workaround is to disable `nbtBackingMapStringCanonicalization` & `optimizeNBTTagCompoundBackingMap` in LoliASM's config file. Will include in the next update.

**Comment by xJon** [comment] 2022-09-03 19:49
Fixed in `1.0.1`.

**Closed by xJon** 2022-09-03 19:49 UTC
Labels: minor bug
