### ISSUE TITLE
Crashing while opening the map

### ISSUE THREAD

**Issue by thomasflrs** [xJon/Tekkit-2#121] opened 2022-10-08 13:14 UTC
The game crashed when I tried to open the large map. I tried it again later, but it worked fine the second time. Here's the crash log: https://mclo.gs/j4mrTVh

**Comment by xJon** [comment] 2022-10-08 13:56
This seems to be a duplicate of https://github.com/xJon/Tekkit-2/issues/103 - hopefully it will get resolved in the next modpack update. Thank you nevertheless for reporting :)

**Closed by xJon** 2022-10-08 13:56 UTC
Labels: duplicate
