### ISSUE TITLE
Alchemical chest + IC2C import upgrade issue

### ISSUE THREAD

**Issue by JNobleA** [xJon/Tekkit-2#87] opened 2022-09-14 13:29 UTC
![2022-09-15_01 33 27](https://user-images.githubusercontent.com/105918849/190168473-f51509aa-04ea-44c4-a2e2-13575774fcde.png)
![2022-09-15_01 34 33](https://user-images.githubusercontent.com/105918849/190168487-f3464ef7-e6cb-4285-bae7-f499e8e0608e.png)
![2022-09-15_01 34 36](https://user-images.githubusercontent.com/105918849/190168492-10519c39-e60a-4a12-950c-e657f9edd6df.png)
![2022-09-15_01 34 39](https://user-images.githubusercontent.com/105918849/190168501-9756f787-a230-4854-bd49-a896cef14c03.png)

**Basic details**
- **Are you using a legitimate Minecraft account?**: YES
- **Are you using Java 8, 64-bit?**: YES
- **Did you add any additional mods**: NO
- **Crash/latest log link (if applicable)**: NA

**Describe the issue**

Using a Rotary macerator with an import upgrade and an export upgrade. The import it taking items from an alchemical chest above the rotary macerator and the export is outputting to an energy condenser next to it. If the rotary macerator is fully powered and you supply the alchemical chest with multiple stacks of items (haven't tested exactly how many are necessary) the macerator will begin grinding the blocks down without actually removing items from the chest. The value of the items in the chest will tick back and forth from 62-63 while somehow still providing items to the macerator. If supplied with nether emerald ore you can produce a red matter block every few seconds if you have 3 macerators around an energy condenser.

**Comment by JNobleA** [comment] 2022-09-14 13:45
> So this is a dupe bug with the rotary macerator? can you reproduce this without an alchemical chest?

I have just done some testing, it only seems to happen with the alchemical chest. 

I have tested:
wooden chest
iron chest
gold chest
diamond chest
crystal chest

**Comment by xJon** [comment] 2022-09-14 13:46
Can you describe the simplest way to reproduce this?

**Comment by JNobleA** [comment] 2022-09-14 13:48
if it's easier feel free to contact me on discord and I can show you, I have screen recordings but they're too large to upload here. JNobleA#9280

**Comment by xJon** [comment] 2022-09-14 13:49
I'd prefer this to be public if you don't mind, would be easier to share with mod developers :)

**Comment by JNobleA** [comment] 2022-09-14 13:58
No worries!

what I have done in my testing:
basic generator setup with copper cables connected to a rotary macerator. Put a stack of ore (ore whatever you want to be macerated) into the macerator. Place an import upgrade and an import upgrade into the macerator, with each being set to their respective chests (importing from alchemical chest, exporting to energy condenser mk1 or mk2). Then place a few stacks of whatever you placed into the macerator into the alchemical chest. The item should then be macerated while the number of items in the alchemical chest does not decrease. 

Notes:
- This only seems to happen with alchemical chests.
- the rotary macerator does not need to be at 100% speed
- the orientation of the alchemical chest or energy condenser does not matter, they can be anywhere around the macerator.
- I don't believe that the energy supply matters. Just that there is enough energy for the macerator.
- This does also work with regular non-rotary macerators, Even if they have overclocker upgrades
![2022-09-15_01 56 21](https://user-images.githubusercontent.com/105918849/190174435-94024761-f1ac-428d-afa1-346c1b43bb2b.png)
![2022-09-15_01 58 19](https://user-images.githubusercontent.com/105918849/190174443-1a9123b6-e98d-4568-a971-c4988f4a3525.png)

**Comment by xJon** [comment] 2022-09-14 14:14
Seems to require at least 2 full stacks in the alchemical chest for the full effect. Will look into it, thanks for the report!

**Comment by xJon** [comment] 2022-09-14 14:16
@Speiger any idea what's happening here with the [alchemical chest](https://github.com/ACGaming/ProjectE/blob/mc1.12.x/src/main/java/moze_intel/projecte/gameObjs/container/AlchChestContainer.java) & import upgrade?

**Comment by JNobleA** [comment] 2022-09-14 14:17
Not technically true, I have just done some testing, If you put only 2 items into the chest as separate stacks it still works. In fact, the first stack slowly increases in size up to 63.

**Comment by xJon** [comment] 2022-09-14 14:20
@JNobleA Cannot reproduce that specifically on my end, but can always reproduce with 2 full stacks in the alchemical chest

**Comment by JNobleA** [comment] 2022-09-14 14:21
> 

Edited my comment, It seemed to only work at slow macerator speeds, At high speeds you need two full stacks.

**Comment by Speiger** [comment] 2022-09-14 14:54
@xJon I looked through both codes. Neither of them seem to be the problem from what I can see...
I will throw this issue on the todolist of things to check after the 1.19.2 beta is done...

Also make sure you don't use to many of these alcs chests because they are havy FPS killers...
(Logic gets executed on client/server and is not split)

**Comment by Speiger** [comment] 2022-10-24 00:19
This should be fixed with the next version.

**Comment by xJon** [comment] 2022-10-28 16:09
@Speiger's fix is included in `1.1.1` :)

**Closed by xJon** 2022-10-28 16:09 UTC
Labels: minor bug, mod issue
