### ISSUE TITLE
Rotary Macerator ALT button to remove upgrade doesn't work

### ISSUE THREAD

**Issue by PawnixHere** [xJon/Tekkit-2#27] opened 2022-08-31 00:27 UTC
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

When the transformer upgrade and energy storage upgrade is placed in a Rotary Macerator, the player is prompted that the upgrade is locked and can't remove the upgrade unless the ALT button is pressed. No matter which button I set the ALT button to be in Minecraft's controls and keybindings, the ALT button does not work. I have tried with a keybind that is red and conflicts with others. When the keybind is yellow (don't know what that means) and when the keybind is white which means that it is not conflicting with anything.

The player is unable to remove the upgrade no matter if the rotary macerator is turned on or off. The only option for the player is to destroy the block and place it out once more.

**Comment by xJon** [comment] 2022-08-31 00:59
Thank you for the report! Closing it as it's a duplicate of https://github.com/xJon/Tekkit-2/issues/7, feel free to follow up there :)

**Closed by xJon** 2022-08-31 00:59 UTC
Labels: duplicate
