### ISSUE TITLE
Ambient/Environment sound issue

### ISSUE THREAD

**Issue by daneshedd** [xJon/Tekkit-2#150] opened 2022-12-09 07:44 UTC
After changing the ambient/ environment sound to anything below 100% and going underwater, it resets it self to 100%.
Makes it very frightening when you come out of the water to super loud wind noises.

**Comment by xJon** [comment] 2022-12-09 07:56
This is a duplicate of https://github.com/xJon/Tekkit-2/issues/13 :)

**Closed by xJon** 2022-12-09 07:56 UTC
Labels: duplicate
