### ISSUE TITLE
Logistics pipes crash

### ISSUE THREAD

**Issue by Vermilliony24** [xJon/Tekkit-2#32] opened 2022-09-01 01:28 UTC
**Basic details**
- **Are you using a legitimate Minecraft account?**:  yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: yes (detail) / ftb utils
- **Crash/latest log link (if applicable)**: link to log / https://mclo.gs/doxwCCa

**Describe the issue**

A clear description of what the issue is.
 when placing pipes, occasionally it crashes, im unable to reliably repeat it, but according to the crash logs basic pipes cause a ticking issue now and then when placing new pipes and causes a crash, sometimes even corrupting the chunk

**Comment by Vermilliony24** [comment] 2022-09-01 15:40
now it seems to happen after placing basic pipes, in fact it crashes when i load in now 

https://mclo.gs/SQvBJBe

**Comment by xJon** [comment] 2022-09-01 15:58
Strange. I've contacted the logistics pipes dev, hopefully they could help.
You could also try to manually update to the latest [alpha version](https://www.curseforge.com/minecraft/mc-mods/logistics-pipes/files/3594848).

**Comment by Vermilliony24** [comment] 2022-09-01 16:00
i'd love to but im on a server, fortunately it only seems to affect me and not anyone else online

**Comment by Vermilliony24** [comment] 2022-09-01 16:14
okay! so removing ftblib and ftbutils allowed me back in! i'll see if i can intentionally repeat it so i can be sure thats what causes it

**Comment by xJon** [comment] 2022-09-01 16:15
Oh? so could be caused by a conflict with them?

**Comment by Vermilliony24** [comment] 2022-09-01 16:32
strange, i've repeated the exact steps that led to a crash with and without ftbutils and ftblib, but i cant recreate it

**Comment by xJon** [comment] 2022-09-01 16:35
@Vermilliony24 Can you re-add those mods and test again?

**Comment by Vermilliony24** [comment] 2022-09-01 16:40
i did, it seems to run just fine, i'll update this if it crashes again

**Comment by Rishum-P** [comment] 2022-09-01 21:14
I can confirm this isn't an isolated bug, a couple of players have been experiencing it on our server, too, but it seems very player specific. I've been unable to re-create it myself.

Player 1: https://mclo.gs/bmYZbBI
Player 2: https://mclo.gs/vCeCNqs

For player 2, we solved it by giving them a config for LoliASM that disabled everything, after attempts to fix it (pack reinstall, removing texture pack etc..) never worked. For player 1, they did a pack reinstall, and it was solved however they only logged in once or twice, so it's unknown whether it's coincidental or it will happen again however, I've asked them to report back if they reencounter it.

It seems only to affect certain players on specific systems, though.

**Comment by xJon** [comment] 2022-09-01 21:53
@Rishum-P Perhaps Player 2 could troubleshoot different config values for LoliASM to try to narrow down causes?

**Comment by Rishum-P** [comment] 2022-09-01 21:58
I'll try my best to convince them to play ball, however, they may be unwilling so I can't promise, unfortunately. I only have the crash reports because they opened a support ticket. I'll do my best to try and figure out the cause though.

**Comment by xJon** [comment] 2022-09-01 22:12
@Rishum-P No worries, it's not your responsibility to figure this one out, either way I'm glad it doesn't affect many players and that they found workarounds.

**Comment by xJon** [comment] 2022-09-06 22:21
Should be fixed in `1.0.3` thanks to @bziemons :)

**Closed by xJon** 2022-09-06 22:21 UTC
Labels: fixed
