### ISSUE TITLE
Geothermal Generator bug with energy loss

### ISSUE THREAD

**Issue by JohanSnurre** [xJon/Tekkit-2#33] opened 2022-09-01 13:20 UTC
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: yes no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

When using ic2 geothermal generator the power generated stops after a while even though there is plenty of "fuel" left in the generator. The UI of the machine also bugs up not showing anything when hovering the UI components

A clear description of what the issue is.

**Comment by xJon** [comment] 2022-09-01 13:50
Couldn't reproduce this issue. You need to make sure the generator has where to send the power.

**Comment by JohanSnurre** [comment] 2022-09-01 14:27
[njgvjmfg.zip](https://github.com/xJon/Tekkit-2/files/9470701/njgvjmfg.zip)
 Here is the save file, Geothermal generator is behind cobblestone wall with smelting setup

**Comment by xJon** [comment] 2022-09-01 14:35
I don't want to or believe it is necessary to test the world, if you want you can reply to my response to better understand this or further troubleshoot.

**Comment by JohanSnurre** [comment] 2022-09-01 14:53
Try this:
1. connect gethermal gen to batbox 
2. connect batbox to some simple machine(macerator, electric furnace)
3. let the batbox fill up/max out on its capacity
For met this deactivates th geothermals and requires a re-place of the block to make it work again

**Comment by xJon** [comment] 2022-09-01 15:09
@JohanSnurre Doesn't this show how the generator stops working when there's no more places to output power to? (because the BatBox is filled up)

**Comment by JohanSnurre** [comment] 2022-09-01 15:12
But the batbox is still providing power to the machines, emptying the power in it. Shouldn't the generator start filling up the batbox if the power in the batbox is below 100%?

**Comment by xJon** [comment] 2022-09-01 15:54
I'm able to reproduce this! Although not this:
> The UI of the machine also bugs up not showing anything when hovering the UI components

@Speiger seems quite minor, but is this intended behavior?
![Gif](https://user-images.githubusercontent.com/8945347/187958643-38487be7-4df7-4135-93dd-ea75543920ef.gif)

**Comment by JohanSnurre** [comment] 2022-09-01 16:21
For me the power transmission from the geo generator stops entirerly. I need to replace the generator and feed it with new fuel for it to transmit again. This cannot be intendet behavior, if so then it is bad design.

**Comment by xJon** [comment] 2022-09-01 16:52
@JohanSnurre Are you reproducing this on a singleplayer world?

**Comment by JohanSnurre** [comment] 2022-09-01 16:56
Yes I am

**Comment by xJon** [comment] 2022-09-01 16:59
As I am unable to reproduce this issue beyond the visual/sound problem, it'd be useful if you can take a short video showing it.

**Comment by JohanSnurre** [comment] 2022-09-01 17:21
https://drive.google.com/drive/folders/1XV-4CZ59KTOkUI3ugCVqMXHce8LD3j06?usp=sharing

Here are some shorts films showing the issue, seems to be working SOME times

**Comment by JohanSnurre** [comment] 2022-09-01 17:25
I also connected the cables to the backs of the generators with no improvements

**Comment by xJon** [comment] 2022-09-01 17:42
@JohanSnurre Can you upload them to Youtube? it'd be easier to view plus have compression as they are currently quite large files. Thanks!

**Comment by Speiger** [comment] 2022-09-01 17:43
I hope i didn't miss read the bug.

@JohanSnurre ok this is basically a really obscure IC2 issue. (any IC2 Versions up to 1.12, yes even those who went before experimental) 
I fixed this bug with 1.19, because I was rewriting the enet anyways.

Basically what the issue is: 
If there is power in the buffer but not enough to overcome the energyloss that the cable has meaning there is 1 EU in there but the nearest target is 1EU energy loss away, it will not send the energy, and the geothermal generator can only refill its buffer when it is completely empty.

How to fix this: Geothermals should be lossless connected to any target it receives.
1: By directly connecting it to power storage of your choice (transformers count as one too), or have the distance so close to the target that there is 0 energy loss.

How i fixed it in 1.19: Basically there is a energy callback if the generator can not send due to powerloss, and it will just refill the powerbuffer instead (if it is empty enough <20EU)

That fix is sadly not easily implementable into 1.12 since the enet implementation is completely different.

**Comment by Speiger** [comment] 2022-09-01 18:04
@JohanSnurre yes the bug i just describ is it.

Also PLEASE for the love of god Look at the item tooltips of the Cables when you have a EU Reader Equipped, you see the exact loss per cable.
And you are using those that have a loss of 0.5EU per block....
You only need Higher tier power cables if your power source (singular) is above 32EU.
Cables work on a per source basis, so if you have 100 10EU sources you still can use Copper cables because its 10EU per packet.

**Comment by xJon** [comment] 2022-09-01 18:26
@JohanSnurre Can you confirm the workaround of lowering the energy loss works? Perhaps switch to glass fibre cables, or use copper cables but with a much shorter distance?

**Comment by xJon** [comment] 2022-09-01 18:50
@JohanSnurre That seems to be a separate issue that comes and goes for me. Could be due to another mod in the pack, I'm not sure, but nonetheless is not game breaking. Thank you for the reports :)

**Comment by Speiger** [comment] 2022-09-01 19:59
> But I still cant hover the internals UI of the geothermal and see the stored energy

@JohanSnurre you need to hover over the meter on the side. Which you didn't do.
Also you need a EU Reader in your hotbar to see the tooltip inside of the gui.

Because that actually makes these visible. (Without a Meter how would you know how much it is... Official lore)

**Comment by xJon** [comment] 2022-09-01 20:06
Thanks for the comment @Speiger, that makes a lot of sense, I didn't know :)

**Comment by xJon** [comment] 2022-09-03 19:56
Unfortunately this is not planned by IC2C to be fixed in 1.12, so I'll close this issue

**Closed by xJon** 2022-09-03 19:56 UTC
Labels: wontfix, minor bug, mod issue, workaround available
