### ISSUE TITLE
IC2 Classic desync issue

### ISSUE THREAD

**Issue by Detonario** [xJon/Tekkit-2#248] opened 2024-04-06 13:40 UTC
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: https://gist.github.com/Detonario/60f72bacc34882df45b37c79df3576c4

**Describe the issue**
If you place a Worldspike (Railcraft) in a world with many machines, the chunks are potentially loaded too quickly (my assumption). In any case, this leads to all machines being rotated by 90 degrees and thus impairing production. You can imagine it this way: When you place down a Solar Panel, it will automatically rearrange to the right position. This rearrangement is ignored by the Worldspike, leading to all Solar Panels and IndustrialCraft Classic machines being loaded the wrong way.

If you remove the Worldspike, the problem persists.

I would be very happy if anyone could help with this issue, as I'm not playing my world anymore because of this bug.

**Pictures**
https://i.imgur.com/NZ8Rnrw.png
https://i.imgur.com/NGjbO22.png

**Comment by xJon** [comment] 2024-04-06 15:10
Does this occur only with a Worldspike and only with Industrial Craft Classic machines?

**Comment by xJon** [comment] 2024-04-06 15:23
Trying to teleport between locations does momentarily render like this:
![image](https://github.com/xJon/Tekkit-2/assets/8945347/a692d09d-a2a1-4552-a4ef-aebb1ef546bc)
But after less than one second updates to the correct machine texture/orientation:
![image](https://github.com/xJon/Tekkit-2/assets/8945347/b0310745-000b-445c-ba85-4ae9aafffbcd)

In this case, it is just a visual delay required by the IC2 Classic mod - and I was able to reproduce it with or without an active Worldspike.
Nevertheless, I believe what you are reporting is different, but again I'm unable to reproduce it.

**Comment by Detonario** [comment] 2024-04-06 15:32
Oh my gosh... I tried something, and I think I'm on the right path. I have used an older version of my world. This version was 1 month ago, and the exact same thing happened. I will write you as soon as I found out more. Thanks!!

It's definitely different for me! The machines stay in the wrong position, and that is not good! I will stay in touch.

**Comment by Detonario** [comment] 2024-04-06 15:40
ok, i think it's not caused by the worldspike, but by Swiftwolf's Rending Gale.

i will try it in a new world as well

**Comment by Detonario** [comment] 2024-04-06 16:44
Okay. After some testing, it's like you said. It's a delay problem. I have tried now on foot, and it happened again. I went on foot to a different place, and came back. Not all of them, but some machines were looking the wrong way.

I go to a different place, while on foot. Then I save and quit, and join back in. Then I go back to the main place, and all the machines from IC2 classic are turned. It seems like it's just a visual problem, because the machines are still working fine.

The cables look very weird, like mini blocks. They are actually loaded as "HV cables", even though I have only used Insulated HV cables so far. So this might be an issue... https://i.imgur.com/uX7CktO.png

I wasn't able to reproduce it in a completely fresh new world, sorry. It seems like one of the mods I have used so far must be the problem. I'm not sure which one of my productions could cause this issue... maybe I should try to go deeper into the backups and try this method every time? What do you think?

**Comment by Detonario** [comment] 2024-04-06 16:59
Edit: You don't need to save & quit. You can just go to another place, and then come back. The machines will be rotated.
I have tried many directions to go to. It only happens when I fly north/east. This is so weird.

**Comment by xJon** [comment] 2024-04-06 17:08
If the machines work, I wouldn't worry about it beyond that. Regarding the cables not loading properly, that might be a duplicate of https://github.com/TinyModularThings/IC2Classic/issues/916, which could be resolved in the next pack update :)
Either way I'd probably close the issue over Railcraft's repository.

**Comment by Detonario** [comment] 2024-04-06 18:52
It's so weird. I tried many directions, but it only happens when I fly over the volcano, which is actually where i spawned the first time when I created this world...

**Comment by Detonario** [comment] 2024-04-06 19:12
Oh my god. I think I'm gonna break out! :D I was able to reproduce it!!! In a new world!

**Comment by Detonario** [comment] 2024-04-06 19:17
https://i.imgur.com/hdKTLMg.png

You just need to build something and fly towards North/East, and if you're "lucky", this should happen.
Do you want the link to the world?

**Comment by Detonario** [comment] 2024-04-06 19:23
https://i.imgur.com/iyPRf6P.png

new world, 2nd attempt

for the 2nd attempt, i tried to go a little bit further, and I went all the way above the clouds

**Comment by xJon** [comment] 2024-04-06 19:24
I will attempt to reproduce!

**Comment by xJon** [comment] 2024-04-06 19:34
💀
![image](https://github.com/xJon/Tekkit-2/assets/8945347/46f25e4d-1d7f-4596-a5f8-9d7301a5157e)

**Comment by Detonario** [comment] 2024-04-06 19:39
worked even better with "render distance = 2 chunks"
https://i.imgur.com/bmDTbgs.png

**Comment by xJon** [comment] 2024-04-06 19:43
Can you reproduce it if you manually update IC2 Classic? https://www.curseforge.com/minecraft/mc-mods/ic2-classic/files/5167044

**Comment by xJon** [comment] 2024-04-06 19:53
I can't seem to reproduce it using IC2C v1.5.9, let me know if you can.

**Comment by Detonario** [comment] 2024-04-06 19:57
hi i'm back

i will try your method in 20 minutes.

i have finished my conclusion:

You can reproduce the problem by flying in one of these directions:
-North/East
-North/West
-South/East
-South/West

You can NOT reproduce it by flying in one of these directions:
-North
-East
-South
-West

**Comment by Detonario** [comment] 2024-04-06 20:05
how do i update it? can i just put the file into the mods folder, or does the new file need to be the same name as "IC2Classic-1.12-1.5.8"

**Comment by xJon** [comment] 2024-04-06 20:06
@Detonario Yes, just in the folder - the name does not matter in this case.

**Comment by Detonario** [comment] 2024-04-06 20:07
okay. should i delete the older version 1.5.8 ?

**Comment by xJon** [comment] 2024-04-06 20:07
@Detonario Yes, or if you have file extensions visible, you can add `.disabled` at the end.

**Comment by Detonario** [comment] 2024-04-06 20:16
yeah, i wasn't able to reproduce it with 1.5.9

**Comment by xJon** [comment] 2024-04-06 20:17
The next pack update should be out this week, with this issue resolved.

**Comment by Detonario** [comment] 2024-04-06 20:19
awesome! did you fix all of that today so fast?

**Comment by Detonario** [comment] 2024-04-06 20:22
oh, i'm dumb. the mod was out there for longer xD anyway, thanks for helping!!

**Comment by Detonario** [comment] 2024-04-07 12:05
Hey, I have found another problem, this time it's actually the Worldspike. Should I create a new ticket or can I tell you here?

**Comment by Detonario** [comment] 2024-04-07 13:15
The Standard Worldspike seems to work fine (even with IC Foregoing), but it doesn't work with Mob Spawners, even though it should, I think?
-> https://i.imgur.com/fy5CFkn.png (assumption that the Standard Worldspike should spawn mobs, but it doesn't)

I have tried building an automatic Essence farm with Mob Crushers from Industrial Foregoing, but the mobs don't spawn
-> https://i.imgur.com/FwXEizV.png
-> https://i.imgur.com/AbHvwbz.png

**Comment by xJon** [comment] 2024-04-07 13:26
@Detonario Standard mob spawners require player presence, not just loaded chunks.

**Comment by Detonario** [comment] 2024-04-07 14:00
So that means I'm not able to build it like that?

**Comment by xJon** [comment] 2024-04-07 14:04
@Detonario You can, but you have to be near a natural spawner for it to be active. That is a vanilla game mechanic.

**Comment by Detonario** [comment] 2024-04-07 14:08
ok, maybe I can use a Teleporter later on in the game...

**Comment by xJon** [comment] 2024-04-07 14:36
You can discuss in Tekkit 2's Discord channel over https://discord.com/invite/technic different ways of creating mob farms :)

**Comment by xJon** [comment] 2024-04-14 01:05
This should be resolved now in `1.2.3`.

**Closed by xJon** 2024-04-14 01:05 UTC
Labels: fixed
