### ISSUE TITLE
Recoloring Alchemical Bags doesn't work on servers

### ISSUE THREAD

**Issue by Sadie80** [xJon/Tekkit-2#95] opened 2022-09-15 17:06 UTC
**Basic details**
- **Are you using a legitimate Minecraft account?**:  yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

Title says it all. Colored bags can not be re-colored, or changed. JEI shows recipes for doing it, but it does not work. Tried several dyes, tried several colored bags. 
![2022-09-12_15 33 01](https://user-images.githubusercontent.com/113623306/190467044-5047fbc5-3ba7-4f6e-bcb1-9f9dde07e6f4.png)

**Comment by xJon** [comment] 2022-09-15 18:46
Can you reproduce this on a server only or also in singleplayer?

**Comment by Jaari** [comment] 2022-09-15 20:57
I cannot reproduce this in singleplayer. However, a more problematic issue occurs: Any contents in the bag are lost when you recolor the bag. Perhaps a server has this disabled because of this issue?

Out of interest, are you using a vanilla crafting table, or a different type of crafting table?

**Comment by xJon** [comment] 2022-09-15 21:00
@ACGaming do you think this would be easy to patch? 👀

**Comment by Jaari** [comment] 2022-09-15 21:09
Just checked, but ProjectRED backpacks keep their contents when recolored.

**Comment by Jaari** [comment] 2022-09-15 21:13
Actually just found out something weird. If you recolor a ProjectE grey bag (containing 1 stack of tnt) to purple, you lose the contents. If you put something else (say a stack of apples) in the purple bag, then recolor it back to grey, you will find the original stack of tnt again. Recoloring the bag back to purple lets you find your apples again.

**Comment by StellarGears** [comment] 2022-09-16 02:27
That is actually an intended feature. Every colored alchemical bag basically acts as a personal, portable enderchest that is tied to bag color, I.e. if you were to craft 3 red alchemical bags, they would all link back to the same exact inventory space, but a 4th blue alchemical bag would instead link to another inventory entirely, only accessible by other blue alchemical bags.

A Wiki Article for Reference:

https://tekkitwiki.com/wiki/Alchemy_Bag

**Comment by xJon** [comment] 2022-09-16 02:39
@StellarGears Thank you for pointing it out! In this case, the only issue would be the lack of a recoloring in multiplayer (and perhaps an addition of some in-game information about them)

**Comment by xJon** [comment] 2022-10-18 01:09
This should be fixed in version `1.1.0` :)

**Closed** 2022-10-18 01:09 UTC
Labels: fixed
