### ISSUE TITLE
Charged klein star too expensive in energy condenser 

### ISSUE THREAD

**Issue by Munchy907** [xJon/Tekkit-2#101] opened 2022-09-16 16:39 UTC
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: no

**Describe the issue**

When you put a charged klein star into a energy condenser it will require the full amount to make the item (including the charge) but only output a none charged klein start
https://prnt.sc/pnFlW8uyHIK4

**Comment by xJon** [comment] 2022-09-16 17:17
Hmm, in Tekkit Classic you weren't able to put charged klein stars in the energy condenser. I do agree that the current behavior isn't great, thanks for the report!

**Comment by xJon** [comment] 2022-10-05 17:20
After talking to @ACGaming, I understand the mod won't touch NBT data probably by design to prevent dupes (e.g. with backpacks). It's *technically* possible to hardcode special care for edge cases like this, albeit risky - If someone wants to they can PR over https://github.com/ACGaming/ProjectE.
Will close this for now, thanks for the report nonetheless!

**Closed by xJon** 2022-10-05 17:20 UTC
Labels: wontfix, minor bug, mod issue, workaround available
