### ISSUE TITLE
 duplication glitch/bug  for over clocker upgrades

### ISSUE THREAD

**Issue by AAddictedGGamer** [xJon/Tekkit-2#212] opened 2023-08-23 19:33 UTC
**Basic details**
- **Are you using a legitimate Minecraft account?**: no
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

https://mclo.gs/63ErH0K

**Describe the issue**

 duplication glitch/bug  for over clocker upgrades when you use 30k coolant cells it doesn't use the 30k coolant cells wires and circuits you just get them back
 
video of what happens 
https://youtu.be/GwCWejed8KY

**Comment by xJon** [comment] 2023-08-23 19:43
I believe this is a duplicate of https://github.com/xJon/Tekkit-2/issues/190. If you want you can test this by manually updating to the [latest version of Universal Tweaks](https://legacy.curseforge.com/minecraft/mc-mods/universal-tweaks/files/4706499).

**Comment by xJon** [comment] 2023-09-03 22:18
Closing this for now as it should be resolved in `1.2.2`.

**Closed by xJon** 2023-09-03 22:18 UTC
Labels: duplicate
