### ISSUE TITLE
Illegal Dupe bug in Tekkit 2

### ISSUE THREAD

**Issue by ColaQuente** [xJon/Tekkit-2#122] opened 2022-10-11 15:03 UTC
**Basic details**
- **Are you using a legitimate Minecraft account?**:  yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

Hello ive found a illegal dupe glitch in latest version of tekkit 2 this bug happens only if i use the alchemical chest on top of ic2 machines using a import upgrade in the machine set to UP, i can smelt infinite items with this combination.
Check the video https://files.fm/f/5ca2wbz6t here i explain in detail.
In the video im in a multiplayer server but ive tested it in single player with success

**Comment by xJon** [comment] 2022-10-11 15:16
Hey, thank you for the report! This seems to be a duplicate of https://github.com/xJon/Tekkit-2/issues/87.

**Closed** 2022-10-18 01:15 UTC
Labels: duplicate
