### ISSUE TITLE
Project Red Relocation crashes

### ISSUE THREAD

**Issue by anqu0re** [xJon/Tekkit-2#58] opened 2022-09-06 02:38 UTC
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: 
Crash log: https://mclo.gs/oqWwdWZ
Crash Report: https://mclo.gs/APivBMd
Log when blocks break: https://mclo.gs/jBsrSih

**Describe the issue**

I am attempting to make a moving platform using frames and frame motors. While doing this I have encountered two bugs. The first is that while the platform is in motion the blocks will occasionally glitch into each other, causing tekkit 2 to crash (crash log and crash report are associated with this problem). The second bug is that sometimes any frames that have panels in them will be deleted causing any wires/levers on them to break. This only seems to occur if the blocks have been moved around a bit, but not necessarily during movement as I have seen the blocks break while the platform is static (log when blocks break is associated with this bug). I have also attached a picture of my setup before and after the blocks break. I have tried updating the ProjectRedRelocation.cfg to change all tile movers to saveload, but this hasn't fixed the second bug (I haven't done enough testing to see if this got rid of the first bug). 

![breaking_blocks](https://user-images.githubusercontent.com/112913230/188534300-ee84a3dc-1cb9-456e-bfa4-aa78d9402e19.png)

**Comment by xJon** [comment] 2022-09-06 13:32
Unfortunately Project Red Relocation is indeed not stable for 1.12.2. Thanks for the reports.
If you have any configuration change suggestions, let me know!

**Comment by anqu0re** [comment] 2022-09-07 02:59
I have done some testing/searching and I found this thread discussing the problem in a different mod pack: https://github.com/MrTJP/ProjectRed/issues/1568
Following what they did I removed the Logistic Pipes mod and that fixed the issue of the forge multipart blocks deleting themselves shortly after movement. However, I still had the issue with the structure sometimes glitching out during movement, crashing tekkit2 (so my changes to the config file did not help with that problem).

**Comment by xJon** [comment] 2022-09-07 03:46
@anqu0re Can you test update `1.0.3` of the modpack with Logistics Pipes installed and report whether the issue is still happening?

**Comment by anqu0re** [comment] 2022-09-07 04:44
I tested the 1.0.3 update and the issue of the forge multipart blocks deleting themselves is still occurring. The log is here if that helps: https://mclo.gs/w08rDlt
Also worth noting is that while my structure is a somewhat complex example, any amount of movement will cause the bug to occur. I was able to trigger the bug by placing a couple of frames in a row, filling some of the frames with panels, and using a frame motor to move them over one block. After waiting about a minute, the frames with panels disappeared.

**Comment by Lumpous** [comment] 2022-09-07 05:38
Looks like an incorrect build of that machine in cooperation with forge settings:
B:removeErroringEntities=true
B:removeErroringTileEntities=true

At first:
Frames have the function to pull anything that they are touching - unless you place a tile on them.
All those cables attached to a tile are not considered a part of the structure, unless you place a nother frame directly next or above them.
That's probably why they to drop/break.

And removing them might be caused by the forge settings whereas forge thinks those tiles do error around.

Will rebuild a moving structure with more detailed explanations when i'm back from work to fully confirm.

**Comment by xJon** [comment] 2022-09-07 11:35
@Lumpous But it seems it also has something to do with Logistics Pipes being installed?

**Comment by Lumpous** [comment] 2022-09-07 11:52
I for now don't see how LP would interact here or even be the cause.
On that screenshot i can't find any LP items or blocks used - but i'll find out once home and rebuild such a moving structure.

**Comment by Lumpous** [comment] 2022-09-22 14:13
I am not taking into account what happened in other and/or older packs.
At the moment it is only of interest if this is really caused by mod interactions between LP and PR, PR and Forge, PR alone or even Forge alone.
Which constelation is the cause here still needs to be clarified.

@Ramog, if you are able to reproduce the mentioned problem, you are welcome to do so and share your results with us for investigation.
In addition, I ask that you enter this observation into the LP tracker so that it can be investigated there.
https://github.com/RS485/LogisticsPipes/issues

**Comment by Ramog** [comment] 2022-09-22 15:35
Well my observation is that I removed Logistics pipes and it doesn't delete the frames anymore. This is also the case for tekkit 2. ^^'

**Comment by ACGaming** [comment] 2022-09-22 16:34
https://github.com/RS485/LogisticsPipes/issues/1456

**Comment by xJon** [comment] 2022-09-22 17:14
@Ramog Would you say the frames are working well enough without Logistics Pipes that they are usable?

**Comment by Ramog** [comment] 2022-09-22 19:14
> @Ramog Would you say the frames are working well enough without Logistics Pipes that they are usable?
atleast in my tests and old worlds in other modpacks
 @anqu0re mentioned that it crashes for him, althought I never had that happen (yet)

**Comment by xJon** [comment] 2022-09-26 17:02
@anqu0re @Ramog Can you please help testing the new Logistics Pipes version that has addressed this issue? You can find the latest version over [this](https://www.curseforge.com/minecraft/mc-mods/logistics-pipes/files/all?filter-game-version=1738749986%3a628) link.

**Comment by xJon** [comment] 2022-10-18 01:00
In version `1.1.0` of the modpack there is a new Logistics Pipes version that addresses the compatibility issues causing frames to disappear. That being said, the crashes are caused and need to be addressed by Project Red. Closing for now as the mod is not in active development and still has a restrictive license.

**Closed** 2022-10-18 01:00 UTC
Labels: wontfix, minor bug, mod issue
