### ISSUE TITLE
RM Furnaces can stop working with Aeternalis Fuel Blocks

### ISSUE THREAD

**Issue by OrangeTrM** [xJon/Tekkit-2#232] opened 2023-11-19 07:09 UTC
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

idk how consistent it is for replicating but if i stick a stack of aeternalis fuel blocks in an rm furnace and keep feeding it things to smelt the rm furnace just stops working after a while and even after replacing the fuel and the items to smelt, it still doesnt start back up
so i switched to just normal aeternalis fuel (not blocks) and it seems to work fine. I was told in the discord to report this on github... so heres the report

**Comment by xJon** [comment] 2023-11-21 02:03
How long did it take until it broke? I just tested for over 2 hours and I could not reproduce the issue.

**Comment by OrangeTrM** [comment] 2023-11-21 04:49
> How long did it take until it broke? I just tested for over 2 hours and I could not reproduce the issue.

I'm not sure how long it takes. I think it's random because I had four RM furnaces, and one of them stopped at 63 blocks of Aeternalis, another at 57, another at 53, and the last one at 46.

**Comment by xJon** [comment] 2023-11-21 14:03
Are you able reproduce the issue in singleplayer or is it specific to a particular server?

**Comment by OrangeTrM** [comment] 2023-11-22 10:26
Seems to happen on servers, not just one but multiple

**Comment by xJon** [comment] 2023-11-22 14:48
I see. And are you able to reproduce the issue on singleplayer?

**Comment by OrangeTrM** [comment] 2023-11-23 06:59
Doesn't seem to do it on singleplayer

**Comment by xJon** [comment] 2023-11-23 15:02
I see. Did you manage to reproduce it on a server that doesn't have further modifications installed beyond the default (e.g. plugins)? Becuase perhaps there's some incompatibility there, rather than with the base modpack.

**Comment by OrangeTrM** [comment] 2023-11-24 16:46
No plugins, no additional mods, just a default tekkit 2 server

**Comment by xJon** [comment] 2023-11-25 01:32
As the mod is not being actively developed and it's not a game-breaking bug, I'll mark this as `wontfix`, but thank you for the report nevertheless.

**Comment by xJon** [comment] 2024-09-08 12:51
Reopened thanks to https://github.com/xJon/Tekkit-2/issues/265, it seems exiting while the furnace works triggers the bug.

**Comment by xJon** [comment] 2024-09-12 19:40
@OrangeTrM @dramurdk This is now fixed in `1.2.4` thanks to @ACGaming's help!

**Closed by xJon** 2024-09-12 19:40 UTC
Labels: minor bug, mod issue
