### ISSUE TITLE
HEI-related crash

### ISSUE THREAD

**Issue by bluesillybeard** [xJon/Tekkit-2#148] opened 2022-12-02 19:36 UTC
**Basic details**
- Using a legit Microsoft account
- Java 19 64 bit, on Manjaro Linux if that has any effect
- No additional mods - just plain Tekkit 2
- crash log: https://mclo.gs/DKuPwUM

**How to reproduce**
- search 'dust' into HEI
- click on silver dust
- click on Fluid Sieving Machine (to the right of the Crafting Table)
- crash

**Comment by xJon** [comment] 2022-12-02 21:50
Seems to be an interaction between Industrial Foregoing to JEI/HEI. Could you please report this over https://github.com/eve0415/IFPatcher/issues ?

**Comment by bluesillybeard** [comment] 2022-12-02 22:28
Yeah I'll report it over there. Thanks!

**Comment by eve0415** [comment] 2022-12-03 01:04
Hello, just saw an issue about this.

You can prevent this crash by changing the config.

https://github.com/LoliKingdom/LoliASM/issues/60

**Comment by bluesillybeard** [comment] 2022-12-03 01:16
I was just about to tell you about it!
I assume you'll set that to the default in the next update?

**Comment by xJon** [comment] 2022-12-03 03:55
Thank you @eve0415!
@bluesillybeard Yes, although strangely this was apparently supposed to be resolved either way, will look into it more.

**Comment by xJon** [comment] 2022-12-03 12:01
It's kind of strange but I can't reproduce this crash.
@bluesillybeard Can you consistently reproduce it? Does it go away if you toggle that config?

**Comment by bluesillybeard** [comment] 2022-12-03 16:29
Huh. I'm able to reproduce it extremely consistently. The issue went away when I changed the config.
Here, I recorded a video:
https://user-images.githubusercontent.com/69832658/205451169-4789bded-0c63-4c0f-9137-5cc1bdb86a7e.mp4

**Comment by xJon** [comment] 2022-12-03 19:39
I will try to ask whether any other players can also reproduce it.

**Comment by xJon** [comment] 2022-12-03 21:37
@bluesillybeard Can you reproduce the crash on a new creative world?

**Comment by bluesillybeard** [comment] 2022-12-04 00:32
Still crashes.

Also, completely deleting and redownloading the pack changed the behavior - now silver dust doesn't crash, but tin still does. And before I changed my settings from the default, it didn't crash at all.

This problem keeps getting more and more confusing lol

**Comment by bluesillybeard** [comment] 2022-12-04 00:34
Since the settings seem to have an effect, here are the ones that I changed from default:
-render distance set to 20 chunks
-music volume set to 0
-GUI scale set to 2
-mipmap levels set to 4
-smooth lighting off

**Comment by xJon** [comment] 2022-12-04 01:03
Can you test to isolate whether it's an issue with mipmaps not being on `0`?

**Comment by bluesillybeard** [comment] 2022-12-04 01:31
It stops crashing when mipmap levels are set to 0, but any other value and it starts crashing.

**Comment by xJon** [comment] 2022-12-04 09:26
In this case despite this edge case I'll keep LoliASM's `releaseSpriteFramesCache` feature enabled for now as it saves on RAM - most players cannot afford playing on mipmap 4, especially with resource packs, and it's also not the default. Thank you for the report nonetheless, and in the future LoliASM is supposed to update to resolve this fully :)

**Comment by bluesillybeard** [comment] 2022-12-04 18:27
Sounds good to me

**Comment by xJon** [comment] 2023-05-29 01:11
Will be fixed in the next version thanks to https://github.com/LoliKingdom/LoliASM/pull/170.

**Comment by xJon** [comment] 2023-09-03 22:17
Should be resolved in `1.2.2`.

**Closed by xJon** 2023-09-03 22:17 UTC
Labels: fixed, mod issue
