### ISSUE TITLE
Watch of Flowing Time crash

### ISSUE THREAD

**Issue by laperoxy** [xJon/Tekkit-2#240] opened 2024-02-10 16:09 UTC
Watch of the flowing time from ProjectE crashes my game every time upon activating it.

**Basic details**
- **Are you using a legitimate Minecraft account?**:  yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: https://mclo.gs/Bqwu7YJ

Upon clicking G while holding Watch of the Flowing time from ProjectE mod, game stops responding and eventually it crashes

**Comment by xJon** [comment] 2024-02-12 00:47
This is a duplicate of https://github.com/xJon/Tekkit-2/issues/229.

**Comment by xJon** [comment] 2024-04-14 01:06
Closing due to inactivity.

**Closed by xJon** 2024-04-14 01:06 UTC
Labels: duplicate
