### ISSUE TITLE
Logistics Pipes can cause a client crash

### ISSUE THREAD

**Issue by K0KS13** [xJon/Tekkit-2#103] opened 2022-09-18 15:23 UTC
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: [link to log](https://mclo.gs/pTrhQ7u)

**Describe the issue**

Minecraft just randomly crashed while flying on server with swiftwolf's ring

**Comment by xJon** [comment] 2022-09-18 17:14
This is most likely due to a Logistics Pipes issue, can you provide your full log and also mention whether you can reproduce the crash?

**Comment by K0KS13** [comment] 2022-09-18 20:05
this was the only log link i got.
I was flying over terrain no bases under me, so i can't really reproduce the crash.

**Comment by SparksSkywere** [comment] 2022-09-25 13:58
Just butting in here with a similar issue during server play, from a player in the server: 

![image](https://user-images.githubusercontent.com/34066194/192146960-d7a97ad5-30d7-475e-88b9-77c1ffd192ac.png)

This happens when players are flying fast around the map and any logistical pipes unrender, crashes can occur when it happens, I have asked for logs specific to this to be sent to me, I will post if you need them!

**Comment by xJon** [comment] 2022-09-25 14:26
@SparksSkywere This will probably be resolved in the next modpack update using the latest Logistics Pipes version.

**Comment by SparksSkywere** [comment] 2022-09-25 14:46
> @SparksSkywere This will probably be resolved in the next modpack update using the latest Logistics Pipes version.

Sweet, I will inform the players!

**Comment by RadegasTCZ** [comment] 2022-10-05 07:09
Talking about logistics pipes, my friend has crashed an entire server by left clicling unrouted pipe, he managed to crash his client 2 times in a row, I can't reproduce it, but the mod version used in this modpack might be buggy.

report: https://mclo.gs/gRkjCG7

**Comment by xJon** [comment] 2022-10-18 01:13
This should be resolved in version `1.1.0`. If you're still having any issues, please report back :)

**Closed by xJon** 2022-10-18 01:13 UTC
Labels: fixed
