### ISSUE TITLE
Crafting a plasma core uses no materials

### ISSUE THREAD

**Issue by CallumADW** [xJon/Tekkit-2#192] opened 2023-05-29 17:11 UTC
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

When crafting a plasma core in a crafting table, it does not use any resources. It appears to, and the correct amount is initially removed from my inventory, but when I re open my inventory, the same amount of materials (advanced alloy, magnets etc) are still present in my inventory. I can provide video evidence if it helps.

**Comment by xJon** [comment] 2023-05-29 17:14
Can you try manually updating the Universal Tweaks mod with [this version](https://cdn.discordapp.com/attachments/1010845591443603516/1109951813106544792/UniversalTweaks-1.12.2-1.6.1-281.jar)?

**Comment by CallumADW** [comment] 2023-05-29 17:30
That fixed the issue. I am playing on a MP server - I just spun up a fresh survival world and it was not present on that with the old UT version so limited to multiplayer only possibly? 
New version works great on MP though!

**Comment by xJon** [comment] 2023-05-29 17:44
Yes it does behave differently on singleplayer and multiplayer, so that makes sense.
Glad it resolved it! In which case I'll close this as it's technically a duplicate of https://github.com/xJon/Tekkit-2/issues/190.
Will be fixed for everyone in the next update :)

**Closed by xJon** 2023-05-29 17:44 UTC
Labels: auto: bug
