### ISSUE TITLE
World closes everytime a tap is used on rubber

### ISSUE THREAD

**Issue by Conquest2020** [xJon/Tekkit-2#17] opened 2022-08-29 19:08 UTC
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**:no
- **Crash/latest log link (if applicable)**: https://mclo.gs/B6qRVpx

**Describe the issue**

Everytime ive went to farm my rubber off the trees as soon as i use the tap on them the world shuts down/Crashes my game entirely.

**Comment by xJon** [comment] 2022-08-29 19:23
This would be a duplicate of https://github.com/xJon/Tekkit-2/issues/12, a system-specific incompatibility.

**Closed by xJon** 2022-08-29 19:23 UTC
Labels: duplicate
