### ISSUE TITLE
VoxelMap Radar missing names & entity visiblity reverts to default after restart

### ISSUE THREAD

**Issue by PawnixHere** [xJon/Tekkit-2#89] opened 2022-09-14 17:34 UTC
No comment
![image](https://user-images.githubusercontent.com/60940047/190223693-b9dc9ec1-381f-483f-9455-ac4884ef74c0.png)

The "Show Neutrals" reverts back to "OFF" upon restart.

**Comment by xJon** [comment] 2022-09-14 17:44
Are you sure it didn't reset due to the modpack update?

**Comment by xJon** [comment] 2022-09-14 22:28
I assume this is a duplicate of https://github.com/xJon/Tekkit-2/issues/88

**Closed by xJon** 2022-09-14 22:28 UTC
Labels: duplicate

**Comment by PawnixHere** [comment] 2022-09-14 22:30
Unless I mentioned the map problem in #88, I'd have to say that it's not a duplicate. I'm glad you already fixed the name issue though, cheers for doing it so fast.

**Comment by xJon** [comment] 2022-09-14 22:32
I assumed that the options reset due to a modpack update. Is that not true?
Regarding the missing names, apologies for (ironically) missing that - it's a mod issue and I'm not planning to modify it, as the mod's author is missing, and the mod has a strict license.

**Comment by PawnixHere** [comment] 2022-09-14 22:35
The options themselves, yes box. No worries. 

It's unfortunate that the mod author is missing :/
I promise that I had nothing to do with it
