### ISSUE TITLE
Saving and quitting can cause the game to freeze

### ISSUE THREAD

**Issue by OpenSauce04** [xJon/Tekkit-2#10] opened 2022-08-28 21:52 UTC
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

As the title says, once the Save and Quit button is pressed while open to LAN, the game stops responding permanently, and the log stops doing anything at all
![image](https://user-images.githubusercontent.com/48618519/187095888-9dd5be74-0ba4-4356-a701-d5ad7885dd32.png)
Last few log messages:
![image](https://user-images.githubusercontent.com/48618519/187095897-c2200665-ba7d-4990-9076-781db4e81418.png)

**Comment by xJon** [comment] 2022-08-28 22:07
Hey, thanks for the report! Unfortunately or not, I'm unable to reproduce this issue, and that end bit of the log seems fine. Does it happen also if no one else has joined your LAN world?

**Comment by ILC5100** [comment] 2022-08-29 09:46
I have the same problem and when the game is not opened in LAN the game crashes also 

and it happens even if no one is jond.

**Comment by xJon** [comment] 2022-08-29 09:49
@ILC5100 Can you share the crash report using https://mclo.gs/ ?

**Comment by ILC5100** [comment] 2022-08-29 09:52
Where can I find the log file?

**Comment by xJon** [comment] 2022-08-29 10:04
Under `crash-reports` in the modpack's installation folder.

**Comment by ILC5100** [comment] 2022-08-29 10:05
The person where this happened does not want to share the crash report

**Comment by xJon** [comment] 2022-08-29 10:20
Okay :)
(I cannot help further without more in-game logs)

**Comment by ILC5100** [comment] 2022-08-29 10:27
I can send my crash report because the same thing happened to me, which part should I send

**Comment by xJon** [comment] 2022-08-29 10:31
@ILC5100 All of it, and please use https://mclo.gs/.

**Comment by ILC5100** [comment] 2022-08-29 10:33
This is the link https://mclo.gs/4lo0GwB

**Comment by xJon** [comment] 2022-08-29 16:09
Do you play in full screen? Do you have a special monitor resolution?

**Comment by OpenSauce04** [comment] 2022-08-29 16:44
I usually play windowed maximized at 1080p

**Comment by xJon** [comment] 2022-09-03 19:53
Can you reproduce this if you make sure to not maximize your window right before saving and quitting?

**Comment by xJon** [comment] 2022-10-05 12:30
Closing for now (will reopen if requested).

**Comment by ILC5100** [comment] 2022-10-11 07:13
I play in window mode and my monitor resolution is 2560×1440p  Gesendet von Mail für Windows Von: JonGesendet: Montag, 29. August 2022 18:09An: xJon/Tekkit-2Cc: ILC5100; MentionBetreff: Re: [xJon/Tekkit-2] Saving and quitting while open to LAN seems to cause the game to freeze permanently; Nothing unusual in logs (Issue #10) Do you play in full screen? Do you have a special monitor resolution?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by xJon** [comment] 2022-10-29 14:42
This happened to me rarely. Unfortunately I cannot reproduce this and I am not aware of the cause.

**Comment by xJon** [comment] 2023-08-19 18:01
This might be resolved by https://github.com/embeddedt/VintageFix/commit/017384a5ddcb282e98a3995e1a48e90305a9bb68

**Comment by xJon** [comment] 2023-09-03 22:16
Hopefully this is fixed in `1.2.2`! If someone still encounters the issue - feel free to comment here.

**Closed by xJon** 2023-09-03 22:16 UTC
Labels: minor bug

**Comment by xJon** [comment] 2025-04-12 05:36
Almost 3 years later this should finally be fixed thanks to https://github.com/embeddedt/VintageFix/commit/d672684f2a55e32dc072d96316c951d70939d67f.
