### ISSUE TITLE
Accessing nuclear chestplates inventories glitch when in blocks or space stations

### ISSUE THREAD

**Issue by TechnoRikkor** [xJon/Tekkit-2#93] opened 2022-09-15 12:05 UTC
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

when trying to open the inventory of advanced nuclear nano chestplate and nuclear quantumsuit jetplate (and likely the nuclear gravitation chestplate. havent made it to test). if you are not wearing any chest piece and try to shift + right click it open, it tries to open the inventory and equips the item at the same time. causing it to bug out the inventory and only fixes when going to the galacticraft menu where everything goes back to its original spots. but it then prevents you from opening its inventory at all, and the only fix is by relogging

**Comment by xJon** [comment] 2022-09-15 17:03
Strange! Are you also pressing `C` when shift right clicking it?

**Comment by TechnoRikkor** [comment] 2022-09-15 17:32
no, simply only shift right click. i can record a clip of it happening to show the bug

**Comment by xJon** [comment] 2022-09-15 17:50
You're supposed to press `C` though in order to access its inventory from what I recall?

**Comment by TechnoRikkor** [comment] 2022-09-15 17:54
i have actually tried both things, the "side inventory key" keybind which is c. doesnt work for it, it usually opens with shift right click (which that in itself is probably also a bug that C doesnt work?) and after my comment, i tried both just incase. only shift right click worked, and only works when wearing some other chest piece

**Comment by xJon** [comment] 2022-09-15 18:36
I see the wiki says shift right click is it, not sure why I remembered it wrong.
Either way I tried shift right clicking it in survival with no chestplate equipped and it works fine for all nuclear jetpacks from both IC2C and Gravisuit Classic, on singleplayer and multiplayer using `1.0.5` and default key bindings.

**Comment by TechnoRikkor** [comment] 2022-09-15 18:39
strange? ive had it constantly happen over and over. if you'd like to see, here is a clip i made of me causing it and i can consistently cause it, ill see if i can get others to replicate the bug or if its somehow only happening to me. real quick ill try another quick test to see if there is another possible cause for its constant trigger https://youtu.be/MtScko8eRTs

**Comment by TechnoRikkor** [comment] 2022-09-15 18:41
ok i did my quick test and found its situational, (ive always tried while living on my space station) and when i went to earth, it did it just fine. try heading to a space station and attempt to open it again, see if you can replicate it

**Comment by xJon** [comment] 2022-09-15 18:42
I doubt it's caused by the current dimension, perhaps by wearing specific Galacticraft gear?

**Comment by TechnoRikkor** [comment] 2022-09-15 18:45
ill take off my entire suit and see if it does

**Comment by TechnoRikkor** [comment] 2022-09-15 18:47
took off my entire space suit and it still happened

**Comment by xJon** [comment] 2022-09-15 19:02
Can you in the overworld teleport inside a block (e.g. when standing on ground do `/tp ~ ~-3 ~`) and try to reproduce the issue?

**Comment by TechnoRikkor** [comment] 2022-09-15 19:08
yes, it replicates it. all items vanish and reappear once entering the galacticraft section, but on the overworld it seems to become fixed, only requiring a relog in multiplayer

**Comment by xJon** [comment] 2022-09-15 19:10
@Speiger could you add looking into this to your todo list or would you prefer me to open an issue somewhere else? This is reproducible with both IC2C & Gravisuit nuclear chestplates of all kinds

**Comment by Speiger** [comment] 2022-09-16 05:18
Yeah... This is a desync issue where for whatever reason the client decides it knows better over the server...
Stuff like this is really annoying... I am not sure if I can fix it...

Well it is fixable, but I have to remove the "Rightclick to equip feature" or move it to a dedicated keybinding that doesn't clash with "Normal rightclick"...

Not sure what to do.
@TechnoRikkor any opinion on this?

**Comment by TechnoRikkor** [comment] 2022-09-18 16:59
to be honest, not many people likely use right click to equip stuff, at most shift right click in their inventory to equip. (at least i do) so removing the nuclear pieces from being able to be right click equipped would very likely fix the issue completely

**Comment by Speiger** [comment] 2022-10-24 17:02
Fixed in the next patch.

**Comment by xJon** [comment] 2022-10-28 16:09
@Speiger's fix is included in `1.1.1` :)

**Closed by xJon** 2022-10-28 16:09 UTC
Labels: minor bug, mod issue, workaround available
