### ISSUE TITLE
Red Matter Furnace Stops working after a game reload

### ISSUE THREAD

**Issue by dramurdk** [xJon/Tekkit-2#265] opened 2024-09-08 08:28 UTC
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

The Red Matter Furnaces stop working after i reload a game.
I tried diffrent material for heating nothing.
They just freez at a point under the process or not start to work at at all.
Thank you.
https://youtu.be/pgjaw_x5sE8 (video for proof)
![rf tekkit 2](https://github.com/user-attachments/assets/c33b5a36-ce79-4342-a273-5b032ff78aff)
![rf2 tekkit 2](https://github.com/user-attachments/assets/5c8e6757-fc80-4643-af1e-6be372d89d15)

**Comment by xJon** [comment] 2024-09-08 12:51
This is a duplicate of https://github.com/xJon/Tekkit-2/issues/232, but thanks to your instructions I am able to reproduce the issue and will try to fix it!

**Closed by xJon** 2024-09-08 12:51 UTC
Labels: duplicate
