### ISSUE TITLE
Quarry bug

### ISSUE THREAD

**Issue by spanky629** [xJon/Tekkit-2#247] opened 2024-04-05 19:18 UTC
**Basic details**
- **Are you using a legitimate Minecraft account?**:  yes
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: attached here  https://mclo.gs/yQVto7s

-->

**Describe the issue**

When using a quarry, you cannot enter the area that the quarry has mined otherwise it is like trying to walk into an invisible forcefield. It lets you enter a few blocks and then it is nearly impossible to escape the glitched movement. This issue persists even after the quarry is completed and destroyed. The chunk that the quarry once occupied basically becomes unusable. In the server log (attached above) it says that the player has "moved incorrectly.

**Comment by xJon** [comment] 2024-04-05 20:23
This is a duplicate of https://github.com/xJon/Tekkit-2/issues/242. Unfortunately I am unable to reproduce this issue on a server.
If you start a new world on your server, can you reproduce the issue? Did you modify the server in any way?

**Comment by xJon** [comment] 2024-04-14 01:07
Closing due to inactivity.

**Closed by xJon** 2024-04-14 01:07 UTC
Labels: duplicate
