### ISSUE TITLE
IC2C sounds in singleplayer stop after game pause

### ISSUE THREAD

**Issue by Defender31** [xJon/Tekkit-2#111] opened 2022-09-26 16:41 UTC
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable
- **Only applies to singleplayer**

**Describe the issue**

When pausing minecraft while ic2 plays a sound eg. Macerator macerating and unpausing it it just will be gone

**Comment by xJon** [comment] 2022-09-26 17:12
@Speiger is this a known issue? Seems to be reproducible only on singleplayer though

**Comment by Speiger** [comment] 2022-09-26 19:18
Not a bug that is intentional.
A audio cleanup when pausing the game.

**Comment by xJon** [comment] 2022-09-26 20:07
Not sure what counts as machine triggers getting triggered, as a bunch of machines can continue to work with existing items and not generate any sound, nevertheless I understand this is intentional

**Comment by Speiger** [comment] 2022-09-26 21:34
> Not sure what counts as machine triggers getting triggered
Every time a Machine starts processing a item it triggers a "Working sound" meaning they will at some point start a looping sound again.

Yeah its not perfect. The sound system technically needs a redesign, but that is out of scope...
Lets put it this way:
I would rather have sounds removed when i pause the Game, then have a bunch of sounds that keep playing even so the machine no longer works or got removed...

**Closed** 2022-09-28 13:23 UTC
Labels: question
