### ISSUE TITLE
Compact Jetpack in logistic Factory

### ISSUE THREAD

**Issue by BombSquadGaming** [xJon/Tekkit-2#215] opened 2023-09-01 01:13 UTC
**Basic details**
- **Are you using a legitimate Minecraft account?**:  yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**
Trying to put a Compact jet pack into my Factory its calling for 8 Advanced circuits and doesn't use all 8 of them, i craft it in a regular crafting table and it only uses 2 one on each side of the recipe and end up with 6 extra but it calls for 8 for it to even show up. 
A clear description of what the issue is.

**Comment by xJon** [comment] 2023-09-01 01:40
I believe this is a duplicate of https://github.com/xJon/Tekkit-2/issues/190. If you want you can test this by manually updating to the [latest version of Universal Tweaks](https://legacy.curseforge.com/minecraft/mc-mods/universal-tweaks/files/4706499).

**Comment by xJon** [comment] 2023-09-03 22:19
Closing this for now as it should be resolved in `1.2.2`.

**Closed by xJon** 2023-09-03 22:19 UTC
Labels: duplicate
