### ISSUE TITLE
Crash: net.minecraftforge.fml.common.LoaderExceptionModCrash

### ISSUE THREAD

**Issue by Mxollier** [xJon/Tekkit-2#31] opened 2022-08-31 15:54 UTC
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: https://mclo.gs/Y5tSI0k and https://mclo.gs/dc9tADP

**Help needed**

Hello

I just downloaded Tekkit 2, played it for a few hours, and when i hit disconnect, a " Minecraft has crashed" message (log link 1) popped up and now a "Minecraft failed to launch" one (log link 2) appears every time i try to launch Tekkit 2. The weird thing is that i have tried to play on a different computer and it works fine. I tried uninstalling Java, Technic and the modpack several times, but nothing works.

The only solution i found was to uninstall the modpack everytime i want to play, as it works the first time...

Could anybody help me with that?

Thanks in advance

**Comment by xJon** [comment] 2022-08-31 16:31
This seems to be a duplicate of https://github.com/xJon/Tekkit-2/issues/1, which will get fixed hopefully in the next modpack update! The current workaround would be to not reassign the left shift key, I'm pretty sure.

**Closed by xJon** 2022-08-31 16:31 UTC
Labels: duplicate

**Comment by Mxollier** [comment] 2022-09-01 11:29
Thanks a lot, works like a charm now
