### ISSUE TITLE
Picking up solar panel seem to crash my game

### ISSUE THREAD

**Issue by MagicChesus** [xJon/Tekkit-2#22] opened 2022-08-30 11:21 UTC
*my first issue request so i'll be filing by the sheet to the dot.*

Today i wanted to relocate my solar panel's (1x lv-solar panel and 1x mv-solar panel) every time i tried to pick them up it crashed.

**Basic details**
- I am using official TechnicLauncher and legit account
- **Are you using Java 8, 64-bit?**: Yes
- **Did you add any additional mods**: no

Links to my several Crash reports:
 - https://mclo.gs/PBJkQsv
 - https://mclo.gs/wQ9HUt7
 - https://mclo.gs/muYIzAF

I don't know what happened but after that i tried once more it crashed completely, didn't even gave me crash report and after that it fixed itself.
So if more info needed i'm here to help.

**Comment by xJon** [comment] 2022-08-30 12:08
This is probably another case of the sound incompatibility but your crash logs are unavailable.

**Comment by MagicChesus** [comment] 2022-08-30 12:33
> This is probably another case of the sound incompatibility but your crash logs are unavailable.

Tried different website for Crash logs hope this work.

**Comment by xJon** [comment] 2022-08-30 12:59
Yes, that works. Seems indeed like a duplicate of https://github.com/xJon/Tekkit-2/issues/12, follow up on that issue for more information about what's happening. Hopefully it can be fixed soon!

**Closed by xJon** 2022-08-30 12:59 UTC
Labels: duplicate
