### ISSUE TITLE
Nano Sabre Activation. Crash! Crash! Crash!

### ISSUE THREAD

**Issue by LividDarkness** [xJon/Tekkit-2#24] opened 2022-08-30 17:10 UTC
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no

When activating a fully charged Nano Sabre it crashes while on a multiplayer server (probably singleplayer too). It will repeat this process over and over and over when logging back in, only if one is fast enough to toss from your inventory when logging in can you save face and continue playing. Problem is you cannot pick the activated sabre back up, as this repeats the issue over and over again. 

Log for the mod creators perusal: https://mclo.gs/xOBt6kS

I think this should be swiftly addressed as this could cause panic for others having a server, people complaining they cant log in because of it. Or forcing servers to roll back causing idk what else to go wrong. But of course y'all working hard and fast of course! Thanks again!

**Comment by xJon** [comment] 2022-08-30 17:38
Do you have any more logs?

**Comment by xJon** [comment] 2022-08-30 17:43
This is most likely yet another duplicate of https://github.com/xJon/Tekkit-2/issues/12.

**Comment by LividDarkness** [comment] 2022-08-30 18:11
no nothing else i can really give other than that log for any crash info

**Comment by LividDarkness** [comment] 2022-08-30 18:27
> This is most likely yet another duplicate of #12.

I seemed to fix the issue by resetting the sounds of IC2. Turn off all sounds and remove all active sounds in IC2 settings. Then you can reactive and play as normal.

Thought id let you know or anyone else reading this thread.

**Comment by xJon** [comment] 2022-08-30 18:48
In this case this is indeed a duplicate of https://github.com/xJon/Tekkit-2/issues/12, thanks for the report and you can follow up there :)

**Closed by xJon** 2022-08-30 18:48 UTC
Labels: duplicate
